### ISSUE TITLE
Screenshot as suggestion

### ISSUE THREAD

**Issue by paulocoutinhox** [mirkorap/stilo#4]
Hi,

First, thanks for the great library.

Can you include screenshots for each example to we understand what happen in practice/visually when use these constants.

Thanks.

**Comment by mirkorap** [comment]
Hi @paulo-coutinho,
during these weekends I will work on Stilo to add some new features and, to other things, improve Readme with code examples and screenshots. Thank you for this suggestion, I appreciate it a lot :)

**Comment by mirkorap** [comment]
Hi @paulo-coutinho, I'm very happy to inform you that a new version of Stilo was released. In this version was introduced the migration to null sound safety and important changes on library utility classes. I took your advice and I created public documentation with some code examples for each constant type. Follow (https://stilo.netlify.app/docs/installation)[https://stilo.netlify.app/docs/installation] to have more information about the library :)
