### ISSUE TITLE
Support Dart Null Sound Safety

### ISSUE THREAD

**Issue by pecostef** [mirkorap/stilo#5]
Hi! First of all let me tell you that I find your package amazing! At the moment it does not support new dart null sound safety and this generates a warning when used inside projects makes apps ran without the "--no-sound-null-safety" failing to start. It would be really great if this package could have null sound safety support! (At the moment I am pretty busy otherwise I would have already created a PR!)

Thanks a lot in advance!

**Comment by mirkorap** [comment]
Hi @pecostef, thanks for appreciating this package :pray:
In these weeks I am working on Stilo to improve some points:
* Add new spacing constants. These are new constants and will not break the existing ones
* Add a new class to position widgets based on Flutter `Positioned` widget
* Support for Dart null sound safety
* Improve Readme file with code examples
* Fix some analysis problems that I found during the usage of the package

In the next release, I want to allow users to override the spacing scale with custom values :slightly_smiling_face: 

I'm working on this package during weekends, but the features that I want to add are a lot :smiley:

**Comment by mirkorap** [comment]
Hi @pecostef, a new version of Stilo was released and includes null sound safety :)
In this release, a lot of breaking changes was made, so before updating check out the new [documentation](https://stilo.netlify.app/docs/installation) about the library
